package com.dianrong.common.auth.server.data.mapper;

import com.dianrong.common.auth.server.data.entity.SlActorVirtualLoan;
import com.dianrong.common.auth.server.data.entity.SlActorVirtualLoanExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlActorVirtualLoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int countByExample(SlActorVirtualLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int deleteByExample(SlActorVirtualLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int insert(SlActorVirtualLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int insertSelective(SlActorVirtualLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    List<SlActorVirtualLoan> selectByExample(SlActorVirtualLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    SlActorVirtualLoan selectByPrimaryKey(BigDecimal aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") SlActorVirtualLoan record, @Param("example") SlActorVirtualLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByExample(@Param("record") SlActorVirtualLoan record, @Param("example") SlActorVirtualLoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByPrimaryKeySelective(SlActorVirtualLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$ACTOR_VIRTUAL_LOAN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByPrimaryKey(SlActorVirtualLoan record);
}