package com.dianrong.common.auth.server.data.mapper;

import com.dianrong.common.auth.server.data.entity.SlBehaviorLog;
import com.dianrong.common.auth.server.data.entity.SlBehaviorLogExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlBehaviorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int countByExample(SlBehaviorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int deleteByExample(SlBehaviorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int insert_mysql(SlBehaviorLog record);
    
    int insert_oracle(SlBehaviorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int insertSelective_mysql(SlBehaviorLog record);
    
    int insertSelective_oracle(SlBehaviorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    List<SlBehaviorLog> selectByExample(SlBehaviorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    SlBehaviorLog selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") SlBehaviorLog record, @Param("example") SlBehaviorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByExample(@Param("record") SlBehaviorLog record, @Param("example") SlBehaviorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByPrimaryKeySelective(SlBehaviorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$BEHAVIOR_LOG
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByPrimaryKey(SlBehaviorLog record);
    
    /**.
     * 根据条件查询数据跳数
     * @param example 条件
     * @return 跳数
     */
    long selectInfoCount(SlBehaviorLogExample example);
    
    /**.
     * 提供分页查询数据的功能(oracle)
     * @param record condtion
     * @return 结果
     */
    List<SlBehaviorLog> selectInfoByPage_Oracle(SlBehaviorLog record);
    
    /**.
     * 提供分页查询数据的功能(mysql)
     * @param record condtion
     * @return 结果
     */
    List<SlBehaviorLog> selectInfoByPage_MySql(SlBehaviorLog record);
}