package com.dianrong.common.auth.server.data.mapper;

import com.dianrong.common.auth.server.data.entity.SlSequence;
import com.dianrong.common.auth.server.data.entity.SlSequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int countByExample(SlSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int deleteByExample(SlSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int insert(SlSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int insertSelective(SlSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    List<SlSequence> selectByExample(SlSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    SlSequence selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") SlSequence record, @Param("example") SlSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByExample(@Param("record") SlSequence record, @Param("example") SlSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByPrimaryKeySelective(SlSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$SEQUENCE
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByPrimaryKey(SlSequence record);
    
    /**.
     * 新加的特殊方法，用于更新cnt的值
     * @param record record
     * @return 影响行数
     */
    int updateCntByNameAndCnt(@Param("record") SlSequence record);
}