package com.dianrong.common.auth.server.data.mapper;

import com.dianrong.common.auth.server.data.entity.SlThirdLogin;
import com.dianrong.common.auth.server.data.entity.SlThirdLoginExample;
import com.dianrong.common.auth.server.data.entity.SlThirdLoginKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlThirdLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int countByExample(SlThirdLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int deleteByExample(SlThirdLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int deleteByPrimaryKey(SlThirdLoginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int insert(SlThirdLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int insertSelective(SlThirdLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    List<SlThirdLogin> selectByExample(SlThirdLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    SlThirdLogin selectByPrimaryKey(SlThirdLoginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") SlThirdLogin record, @Param("example") SlThirdLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByExample(@Param("record") SlThirdLogin record, @Param("example") SlThirdLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByPrimaryKeySelective(SlThirdLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SL$THIRD_LOGIN
     *
     * @mbggenerated Thu May 05 10:43:21 CST 2016
     */
    int updateByPrimaryKey(SlThirdLogin record);
}