package com.dianrong.common.uniauth.server.data.entity;

import java.util.ArrayList;
import java.util.List;

public class AttributeExtendExample extends PageParam {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public AttributeExtendExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCodeIsNull() {
      addCriterion("code is null");
      return (Criteria) this;
    }

    public Criteria andCodeIsNotNull() {
      addCriterion("code is not null");
      return (Criteria) this;
    }

    public Criteria andCodeEqualTo(String value) {
      addCriterion("code =", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotEqualTo(String value) {
      addCriterion("code <>", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThan(String value) {
      addCriterion("code >", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThanOrEqualTo(String value) {
      addCriterion("code >=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThan(String value) {
      addCriterion("code <", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThanOrEqualTo(String value) {
      addCriterion("code <=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLike(String value) {
      addCriterion("code like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotLike(String value) {
      addCriterion("code not like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeIn(List<String> values) {
      addCriterion("code in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotIn(List<String> values) {
      addCriterion("code not in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeBetween(String value1, String value2) {
      addCriterion("code between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotBetween(String value1, String value2) {
      addCriterion("code not between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andCategoryIsNull() {
      addCriterion("category is null");
      return (Criteria) this;
    }

    public Criteria andCategoryIsNotNull() {
      addCriterion("category is not null");
      return (Criteria) this;
    }

    public Criteria andCategoryEqualTo(String value) {
      addCriterion("category =", value, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryNotEqualTo(String value) {
      addCriterion("category <>", value, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryGreaterThan(String value) {
      addCriterion("category >", value, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryGreaterThanOrEqualTo(String value) {
      addCriterion("category >=", value, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryLessThan(String value) {
      addCriterion("category <", value, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryLessThanOrEqualTo(String value) {
      addCriterion("category <=", value, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryLike(String value) {
      addCriterion("category like", value, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryNotLike(String value) {
      addCriterion("category not like", value, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryIn(List<String> values) {
      addCriterion("category in", values, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryNotIn(List<String> values) {
      addCriterion("category not in", values, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryBetween(String value1, String value2) {
      addCriterion("category between", value1, value2, "category");
      return (Criteria) this;
    }

    public Criteria andCategoryNotBetween(String value1, String value2) {
      addCriterion("category not between", value1, value2, "category");
      return (Criteria) this;
    }

    public Criteria andSubcategoryIsNull() {
      addCriterion("subcategory is null");
      return (Criteria) this;
    }

    public Criteria andSubcategoryIsNotNull() {
      addCriterion("subcategory is not null");
      return (Criteria) this;
    }

    public Criteria andSubcategoryEqualTo(String value) {
      addCriterion("subcategory =", value, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryNotEqualTo(String value) {
      addCriterion("subcategory <>", value, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryGreaterThan(String value) {
      addCriterion("subcategory >", value, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryGreaterThanOrEqualTo(String value) {
      addCriterion("subcategory >=", value, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryLessThan(String value) {
      addCriterion("subcategory <", value, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryLessThanOrEqualTo(String value) {
      addCriterion("subcategory <=", value, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryLike(String value) {
      addCriterion("subcategory like", value, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryNotLike(String value) {
      addCriterion("subcategory not like", value, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryIn(List<String> values) {
      addCriterion("subcategory in", values, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryNotIn(List<String> values) {
      addCriterion("subcategory not in", values, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryBetween(String value1, String value2) {
      addCriterion("subcategory between", value1, value2, "subcategory");
      return (Criteria) this;
    }

    public Criteria andSubcategoryNotBetween(String value1, String value2) {
      addCriterion("subcategory not between", value1, value2, "subcategory");
      return (Criteria) this;
    }

    public Criteria andDescriptionIsNull() {
      addCriterion("description is null");
      return (Criteria) this;
    }

    public Criteria andDescriptionIsNotNull() {
      addCriterion("description is not null");
      return (Criteria) this;
    }

    public Criteria andDescriptionEqualTo(String value) {
      addCriterion("description =", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotEqualTo(String value) {
      addCriterion("description <>", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionGreaterThan(String value) {
      addCriterion("description >", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
      addCriterion("description >=", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLessThan(String value) {
      addCriterion("description <", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLessThanOrEqualTo(String value) {
      addCriterion("description <=", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLike(String value) {
      addCriterion("description like", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotLike(String value) {
      addCriterion("description not like", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionIn(List<String> values) {
      addCriterion("description in", values, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotIn(List<String> values) {
      addCriterion("description not in", values, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionBetween(String value1, String value2) {
      addCriterion("description between", value1, value2, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotBetween(String value1, String value2) {
      addCriterion("description not between", value1, value2, "description");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIsNull() {
      addCriterion("tenancy_id is null");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIsNotNull() {
      addCriterion("tenancy_id is not null");
      return (Criteria) this;
    }

    public Criteria andTenancyIdEqualTo(Long value) {
      addCriterion("tenancy_id =", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotEqualTo(Long value) {
      addCriterion("tenancy_id <>", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdGreaterThan(Long value) {
      addCriterion("tenancy_id >", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdGreaterThanOrEqualTo(Long value) {
      addCriterion("tenancy_id >=", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdLessThan(Long value) {
      addCriterion("tenancy_id <", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdLessThanOrEqualTo(Long value) {
      addCriterion("tenancy_id <=", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIn(List<Long> values) {
      addCriterion("tenancy_id in", values, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotIn(List<Long> values) {
      addCriterion("tenancy_id not in", values, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdBetween(Long value1, Long value2) {
      addCriterion("tenancy_id between", value1, value2, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotBetween(Long value1, Long value2) {
      addCriterion("tenancy_id not between", value1, value2, "tenancyId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated do_not_delete_during_merge Thu Jun 01 18:13:03 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}
