package com.dianrong.common.uniauth.server.data.entity;

public class Cfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg.id
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg.key
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg.type
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg.value
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg.file
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    private byte[] file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg.id
     *
     * @return the value of cfg.id
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg.id
     *
     * @param id the value for cfg.id
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg.key
     *
     * @return the value of cfg.key
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg.key
     *
     * @param key the value for cfg.key
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg.type
     *
     * @return the value of cfg.type
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg.type
     *
     * @param type the value for cfg.type
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg.value
     *
     * @return the value of cfg.value
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg.value
     *
     * @param value the value for cfg.value
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg.file
     *
     * @return the value of cfg.file
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public byte[] getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg.file
     *
     * @param file the value for cfg.file
     *
     * @mbggenerated Fri Mar 25 17:14:05 CST 2016
     */
    public void setFile(byte[] file) {
        this.file = file;
    }
}