package com.dianrong.common.uniauth.server.data.entity;

public class CfgType {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * cfg_type.id
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * cfg_type.code
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String code;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column cfg_type.id
   *
   * @return the value of cfg_type.id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column cfg_type.id
   *
   * @param id the value for cfg_type.id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column cfg_type.code
   *
   * @return the value of cfg_type.code
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column cfg_type.code
   *
   * @param code the value for cfg_type.code
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setCode(String code) {
    this.code = code;
  }
}
