package com.dianrong.common.uniauth.server.data.entity;

import java.util.Date;

public class Domain {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * domain.id
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * domain.code
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String code;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * domain.display_name
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String displayName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * domain.description
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String description;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * domain.status
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Byte status;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * domain.tenancy_id
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Long tenancyId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * domain.create_date
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Date createDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * domain.last_update
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Date lastUpdate;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column domain.id
   *
   * @return the value of domain.id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column domain.id
   *
   * @param id the value for domain.id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column domain.code
   *
   * @return the value of domain.code
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column domain.code
   *
   * @param code the value for domain.code
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setCode(String code) {
    this.code = code;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column domain.display_name
   *
   * @return the value of domain.display_name
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getDisplayName() {
    return displayName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column domain.display_name
   *
   * @param displayName the value for domain.display_name
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column domain.description
   *
   * @return the value of domain.description
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getDescription() {
    return description;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column domain.description
   *
   * @param description the value for domain.description
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column domain.status
   *
   * @return the value of domain.status
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Byte getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column domain.status
   *
   * @param status the value for domain.status
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setStatus(Byte status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column domain.tenancy_id
   *
   * @return the value of domain.tenancy_id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Long getTenancyId() {
    return tenancyId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column domain.tenancy_id
   *
   * @param tenancyId the value for domain.tenancy_id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setTenancyId(Long tenancyId) {
    this.tenancyId = tenancyId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column domain.create_date
   *
   * @return the value of domain.create_date
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Date getCreateDate() {
    return createDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column domain.create_date
   *
   * @param createDate the value for domain.create_date
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column domain.last_update
   *
   * @return the value of domain.last_update
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Date getLastUpdate() {
    return lastUpdate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column domain.last_update
   *
   * @param lastUpdate the value for domain.last_update
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setLastUpdate(Date lastUpdate) {
    this.lastUpdate = lastUpdate;
  }
}
