package com.dianrong.common.uniauth.server.data.entity;

public class GroupPathKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_path.ancestor
     *
     * @mbggenerated Fri Jan 15 14:30:43 CST 2016
     */
    private Integer ancestor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_path.descendant
     *
     * @mbggenerated Fri Jan 15 14:30:43 CST 2016
     */
    private Integer descendant;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_path.ancestor
     *
     * @return the value of group_path.ancestor
     *
     * @mbggenerated Fri Jan 15 14:30:43 CST 2016
     */
    public Integer getAncestor() {
        return ancestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_path.ancestor
     *
     * @param ancestor the value for group_path.ancestor
     *
     * @mbggenerated Fri Jan 15 14:30:43 CST 2016
     */
    public void setAncestor(Integer ancestor) {
        this.ancestor = ancestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_path.descendant
     *
     * @return the value of group_path.descendant
     *
     * @mbggenerated Fri Jan 15 14:30:43 CST 2016
     */
    public Integer getDescendant() {
        return descendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_path.descendant
     *
     * @param descendant the value for group_path.descendant
     *
     * @mbggenerated Fri Jan 15 14:30:43 CST 2016
     */
    public void setDescendant(Integer descendant) {
        this.descendant = descendant;
    }
}