package com.dianrong.common.uniauth.server.data.entity;

public class GroupPath extends GroupPathKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_path.deepth
     *
     * @mbggenerated Thu Jan 14 17:06:54 CST 2016
     */
    private Byte deepth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_path.deepth
     *
     * @return the value of group_path.deepth
     *
     * @mbggenerated Thu Jan 14 17:06:54 CST 2016
     */
    public Byte getDeepth() {
        return deepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_path.deepth
     *
     * @param deepth the value for group_path.deepth
     *
     * @mbggenerated Thu Jan 14 17:06:54 CST 2016
     */
    public void setDeepth(Byte deepth) {
        this.deepth = deepth;
    }
}