package com.dianrong.common.uniauth.server.data.entity;

import lombok.ToString;

@ToString
public class GrpAttributeRecords extends AttributeRecords {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * grp_attribute_records.grp_id
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  private Integer grpId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column grp_attribute_records.grp_id
   *
   * @return the value of grp_attribute_records.grp_id
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public Integer getGrpId() {
    return grpId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column grp_attribute_records.grp_id
   *
   * @param grpId the value for grp_attribute_records.grp_id
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void setGrpId(Integer grpId) {
    this.grpId = grpId;
  }
}
