package com.dianrong.common.uniauth.server.data.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HrSynchronousLogExample extends PageParam{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public HrSynchronousLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeIsNull() {
            addCriterion("synchronous_start_time is null");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeIsNotNull() {
            addCriterion("synchronous_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeEqualTo(Date value) {
            addCriterion("synchronous_start_time =", value, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeNotEqualTo(Date value) {
            addCriterion("synchronous_start_time <>", value, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeGreaterThan(Date value) {
            addCriterion("synchronous_start_time >", value, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("synchronous_start_time >=", value, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeLessThan(Date value) {
            addCriterion("synchronous_start_time <", value, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("synchronous_start_time <=", value, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeIn(List<Date> values) {
            addCriterion("synchronous_start_time in", values, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeNotIn(List<Date> values) {
            addCriterion("synchronous_start_time not in", values, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeBetween(Date value1, Date value2) {
            addCriterion("synchronous_start_time between", value1, value2, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("synchronous_start_time not between", value1, value2, "synchronousStartTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeIsNull() {
            addCriterion("synchronous_end_time is null");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeIsNotNull() {
            addCriterion("synchronous_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeEqualTo(Date value) {
            addCriterion("synchronous_end_time =", value, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeNotEqualTo(Date value) {
            addCriterion("synchronous_end_time <>", value, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeGreaterThan(Date value) {
            addCriterion("synchronous_end_time >", value, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("synchronous_end_time >=", value, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeLessThan(Date value) {
            addCriterion("synchronous_end_time <", value, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("synchronous_end_time <=", value, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeIn(List<Date> values) {
            addCriterion("synchronous_end_time in", values, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeNotIn(List<Date> values) {
            addCriterion("synchronous_end_time not in", values, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeBetween(Date value1, Date value2) {
            addCriterion("synchronous_end_time between", value1, value2, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("synchronous_end_time not between", value1, value2, "synchronousEndTime");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeIsNull() {
            addCriterion("synchronous_type is null");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeIsNotNull() {
            addCriterion("synchronous_type is not null");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeEqualTo(String value) {
            addCriterion("synchronous_type =", value, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeNotEqualTo(String value) {
            addCriterion("synchronous_type <>", value, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeGreaterThan(String value) {
            addCriterion("synchronous_type >", value, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeGreaterThanOrEqualTo(String value) {
            addCriterion("synchronous_type >=", value, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeLessThan(String value) {
            addCriterion("synchronous_type <", value, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeLessThanOrEqualTo(String value) {
            addCriterion("synchronous_type <=", value, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeLike(String value) {
            addCriterion("synchronous_type like", value, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeNotLike(String value) {
            addCriterion("synchronous_type not like", value, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeIn(List<String> values) {
            addCriterion("synchronous_type in", values, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeNotIn(List<String> values) {
            addCriterion("synchronous_type not in", values, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeBetween(String value1, String value2) {
            addCriterion("synchronous_type between", value1, value2, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andSynchronousTypeNotBetween(String value1, String value2) {
            addCriterion("synchronous_type not between", value1, value2, "synchronousType");
            return (Criteria) this;
        }

        public Criteria andProcessContentIsNull() {
            addCriterion("process_content is null");
            return (Criteria) this;
        }

        public Criteria andProcessContentIsNotNull() {
            addCriterion("process_content is not null");
            return (Criteria) this;
        }

        public Criteria andProcessContentEqualTo(String value) {
            addCriterion("process_content =", value, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentNotEqualTo(String value) {
            addCriterion("process_content <>", value, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentGreaterThan(String value) {
            addCriterion("process_content >", value, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentGreaterThanOrEqualTo(String value) {
            addCriterion("process_content >=", value, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentLessThan(String value) {
            addCriterion("process_content <", value, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentLessThanOrEqualTo(String value) {
            addCriterion("process_content <=", value, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentLike(String value) {
            addCriterion("process_content like", value, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentNotLike(String value) {
            addCriterion("process_content not like", value, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentIn(List<String> values) {
            addCriterion("process_content in", values, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentNotIn(List<String> values) {
            addCriterion("process_content not in", values, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentBetween(String value1, String value2) {
            addCriterion("process_content between", value1, value2, "processContent");
            return (Criteria) this;
        }

        public Criteria andProcessContentNotBetween(String value1, String value2) {
            addCriterion("process_content not between", value1, value2, "processContent");
            return (Criteria) this;
        }

        public Criteria andComputerIpIsNull() {
            addCriterion("computer_ip is null");
            return (Criteria) this;
        }

        public Criteria andComputerIpIsNotNull() {
            addCriterion("computer_ip is not null");
            return (Criteria) this;
        }

        public Criteria andComputerIpEqualTo(String value) {
            addCriterion("computer_ip =", value, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpNotEqualTo(String value) {
            addCriterion("computer_ip <>", value, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpGreaterThan(String value) {
            addCriterion("computer_ip >", value, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpGreaterThanOrEqualTo(String value) {
            addCriterion("computer_ip >=", value, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpLessThan(String value) {
            addCriterion("computer_ip <", value, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpLessThanOrEqualTo(String value) {
            addCriterion("computer_ip <=", value, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpLike(String value) {
            addCriterion("computer_ip like", value, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpNotLike(String value) {
            addCriterion("computer_ip not like", value, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpIn(List<String> values) {
            addCriterion("computer_ip in", values, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpNotIn(List<String> values) {
            addCriterion("computer_ip not in", values, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpBetween(String value1, String value2) {
            addCriterion("computer_ip between", value1, value2, "computerIp");
            return (Criteria) this;
        }

        public Criteria andComputerIpNotBetween(String value1, String value2) {
            addCriterion("computer_ip not between", value1, value2, "computerIp");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultIsNull() {
            addCriterion("synchronous_result is null");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultIsNotNull() {
            addCriterion("synchronous_result is not null");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultEqualTo(String value) {
            addCriterion("synchronous_result =", value, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultNotEqualTo(String value) {
            addCriterion("synchronous_result <>", value, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultGreaterThan(String value) {
            addCriterion("synchronous_result >", value, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultGreaterThanOrEqualTo(String value) {
            addCriterion("synchronous_result >=", value, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultLessThan(String value) {
            addCriterion("synchronous_result <", value, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultLessThanOrEqualTo(String value) {
            addCriterion("synchronous_result <=", value, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultLike(String value) {
            addCriterion("synchronous_result like", value, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultNotLike(String value) {
            addCriterion("synchronous_result not like", value, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultIn(List<String> values) {
            addCriterion("synchronous_result in", values, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultNotIn(List<String> values) {
            addCriterion("synchronous_result not in", values, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultBetween(String value1, String value2) {
            addCriterion("synchronous_result between", value1, value2, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andSynchronousResultNotBetween(String value1, String value2) {
            addCriterion("synchronous_result not between", value1, value2, "synchronousResult");
            return (Criteria) this;
        }

        public Criteria andFailureMsgIsNull() {
            addCriterion("failure_msg is null");
            return (Criteria) this;
        }

        public Criteria andFailureMsgIsNotNull() {
            addCriterion("failure_msg is not null");
            return (Criteria) this;
        }

        public Criteria andFailureMsgEqualTo(String value) {
            addCriterion("failure_msg =", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgNotEqualTo(String value) {
            addCriterion("failure_msg <>", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgGreaterThan(String value) {
            addCriterion("failure_msg >", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgGreaterThanOrEqualTo(String value) {
            addCriterion("failure_msg >=", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgLessThan(String value) {
            addCriterion("failure_msg <", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgLessThanOrEqualTo(String value) {
            addCriterion("failure_msg <=", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgLike(String value) {
            addCriterion("failure_msg like", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgNotLike(String value) {
            addCriterion("failure_msg not like", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgIn(List<String> values) {
            addCriterion("failure_msg in", values, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgNotIn(List<String> values) {
            addCriterion("failure_msg not in", values, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgBetween(String value1, String value2) {
            addCriterion("failure_msg between", value1, value2, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgNotBetween(String value1, String value2) {
            addCriterion("failure_msg not between", value1, value2, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNull() {
            addCriterion("last_update is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNotNull() {
            addCriterion("last_update is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateEqualTo(Date value) {
            addCriterion("last_update =", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotEqualTo(Date value) {
            addCriterion("last_update <>", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThan(Date value) {
            addCriterion("last_update >", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update >=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThan(Date value) {
            addCriterion("last_update <", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThanOrEqualTo(Date value) {
            addCriterion("last_update <=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIn(List<Date> values) {
            addCriterion("last_update in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotIn(List<Date> values) {
            addCriterion("last_update not in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateBetween(Date value1, Date value2) {
            addCriterion("last_update between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotBetween(Date value1, Date value2) {
            addCriterion("last_update not between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 30 17:11:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
