package com.dianrong.common.uniauth.server.data.entity;

import java.util.Date;

public class HrSynchronousLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.id
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.synchronous_start_time
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private Date synchronousStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.synchronous_end_time
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private Date synchronousEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.synchronous_type
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private String synchronousType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.process_content
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private String processContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.computer_ip
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private String computerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.synchronous_result
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private String synchronousResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.failure_msg
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private String failureMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.create_date
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_synchronous_log.last_update
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.id
     *
     * @return the value of hr_synchronous_log.id
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.id
     *
     * @param id the value for hr_synchronous_log.id
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.synchronous_start_time
     *
     * @return the value of hr_synchronous_log.synchronous_start_time
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public Date getSynchronousStartTime() {
        return synchronousStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.synchronous_start_time
     *
     * @param synchronousStartTime the value for hr_synchronous_log.synchronous_start_time
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setSynchronousStartTime(Date synchronousStartTime) {
        this.synchronousStartTime = synchronousStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.synchronous_end_time
     *
     * @return the value of hr_synchronous_log.synchronous_end_time
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public Date getSynchronousEndTime() {
        return synchronousEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.synchronous_end_time
     *
     * @param synchronousEndTime the value for hr_synchronous_log.synchronous_end_time
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setSynchronousEndTime(Date synchronousEndTime) {
        this.synchronousEndTime = synchronousEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.synchronous_type
     *
     * @return the value of hr_synchronous_log.synchronous_type
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public String getSynchronousType() {
        return synchronousType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.synchronous_type
     *
     * @param synchronousType the value for hr_synchronous_log.synchronous_type
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setSynchronousType(String synchronousType) {
        this.synchronousType = synchronousType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.process_content
     *
     * @return the value of hr_synchronous_log.process_content
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public String getProcessContent() {
        return processContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.process_content
     *
     * @param processContent the value for hr_synchronous_log.process_content
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setProcessContent(String processContent) {
        this.processContent = processContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.computer_ip
     *
     * @return the value of hr_synchronous_log.computer_ip
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public String getComputerIp() {
        return computerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.computer_ip
     *
     * @param computerIp the value for hr_synchronous_log.computer_ip
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setComputerIp(String computerIp) {
        this.computerIp = computerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.synchronous_result
     *
     * @return the value of hr_synchronous_log.synchronous_result
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public String getSynchronousResult() {
        return synchronousResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.synchronous_result
     *
     * @param synchronousResult the value for hr_synchronous_log.synchronous_result
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setSynchronousResult(String synchronousResult) {
        this.synchronousResult = synchronousResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.failure_msg
     *
     * @return the value of hr_synchronous_log.failure_msg
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public String getFailureMsg() {
        return failureMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.failure_msg
     *
     * @param failureMsg the value for hr_synchronous_log.failure_msg
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setFailureMsg(String failureMsg) {
        this.failureMsg = failureMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.create_date
     *
     * @return the value of hr_synchronous_log.create_date
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.create_date
     *
     * @param createDate the value for hr_synchronous_log.create_date
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_synchronous_log.last_update
     *
     * @return the value of hr_synchronous_log.last_update
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_synchronous_log.last_update
     *
     * @param lastUpdate the value for hr_synchronous_log.last_update
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}