package com.dianrong.common.uniauth.server.data.entity;

public class TagType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_type.id
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_type.code
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_type.domain_id
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    private Integer domainId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_type.id
     *
     * @return the value of tag_type.id
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_type.id
     *
     * @param id the value for tag_type.id
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_type.code
     *
     * @return the value of tag_type.code
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_type.code
     *
     * @param code the value for tag_type.code
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_type.domain_id
     *
     * @return the value of tag_type.domain_id
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_type.domain_id
     *
     * @param domainId the value for tag_type.domain_id
     *
     * @mbggenerated Thu Apr 07 16:46:03 CST 2016
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }
}