package com.dianrong.common.uniauth.server.data.entity;

import java.util.ArrayList;
import java.util.List;

public class TagTypeExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public TagTypeExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Integer value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Integer value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Integer value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Integer value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Integer value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Integer value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Integer> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Integer> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Integer value1, Integer value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Integer value1, Integer value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCodeIsNull() {
      addCriterion("code is null");
      return (Criteria) this;
    }

    public Criteria andCodeIsNotNull() {
      addCriterion("code is not null");
      return (Criteria) this;
    }

    public Criteria andCodeEqualTo(String value) {
      addCriterion("code =", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotEqualTo(String value) {
      addCriterion("code <>", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThan(String value) {
      addCriterion("code >", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThanOrEqualTo(String value) {
      addCriterion("code >=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThan(String value) {
      addCriterion("code <", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThanOrEqualTo(String value) {
      addCriterion("code <=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLike(String value) {
      addCriterion("code like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotLike(String value) {
      addCriterion("code not like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeIn(List<String> values) {
      addCriterion("code in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotIn(List<String> values) {
      addCriterion("code not in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeBetween(String value1, String value2) {
      addCriterion("code between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotBetween(String value1, String value2) {
      addCriterion("code not between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andDomainIdIsNull() {
      addCriterion("domain_id is null");
      return (Criteria) this;
    }

    public Criteria andDomainIdIsNotNull() {
      addCriterion("domain_id is not null");
      return (Criteria) this;
    }

    public Criteria andDomainIdEqualTo(Integer value) {
      addCriterion("domain_id =", value, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdNotEqualTo(Integer value) {
      addCriterion("domain_id <>", value, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdGreaterThan(Integer value) {
      addCriterion("domain_id >", value, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdGreaterThanOrEqualTo(Integer value) {
      addCriterion("domain_id >=", value, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdLessThan(Integer value) {
      addCriterion("domain_id <", value, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdLessThanOrEqualTo(Integer value) {
      addCriterion("domain_id <=", value, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdIn(List<Integer> values) {
      addCriterion("domain_id in", values, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdNotIn(List<Integer> values) {
      addCriterion("domain_id not in", values, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdBetween(Integer value1, Integer value2) {
      addCriterion("domain_id between", value1, value2, "domainId");
      return (Criteria) this;
    }

    public Criteria andDomainIdNotBetween(Integer value1, Integer value2) {
      addCriterion("domain_id not between", value1, value2, "domainId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIsNull() {
      addCriterion("tenancy_id is null");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIsNotNull() {
      addCriterion("tenancy_id is not null");
      return (Criteria) this;
    }

    public Criteria andTenancyIdEqualTo(Long value) {
      addCriterion("tenancy_id =", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotEqualTo(Long value) {
      addCriterion("tenancy_id <>", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdGreaterThan(Long value) {
      addCriterion("tenancy_id >", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdGreaterThanOrEqualTo(Long value) {
      addCriterion("tenancy_id >=", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdLessThan(Long value) {
      addCriterion("tenancy_id <", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdLessThanOrEqualTo(Long value) {
      addCriterion("tenancy_id <=", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIn(List<Long> values) {
      addCriterion("tenancy_id in", values, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotIn(List<Long> values) {
      addCriterion("tenancy_id not in", values, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdBetween(Long value1, Long value2) {
      addCriterion("tenancy_id between", value1, value2, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotBetween(Long value1, Long value2) {
      addCriterion("tenancy_id not between", value1, value2, "tenancyId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * tag_type
   *
   * @mbggenerated do_not_delete_during_merge Tue Sep 27 11:53:21 CST 2016
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * tag_type
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}
