package com.dianrong.common.uniauth.server.data.entity;

import java.util.Date;

public class Tenancy {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.id
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.code
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String code;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.name
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.contact_name
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String contactName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.phone
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String phone;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.description
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private String description;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.status
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Byte status;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.create_date
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Date createDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tenancy.last_update
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Date lastUpdate;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.id
   *
   * @return the value of tenancy.id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.id
   *
   * @param id the value for tenancy.id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.code
   *
   * @return the value of tenancy.code
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.code
   *
   * @param code the value for tenancy.code
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setCode(String code) {
    this.code = code;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.name
   *
   * @return the value of tenancy.name
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.name
   *
   * @param name the value for tenancy.name
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.contact_name
   *
   * @return the value of tenancy.contact_name
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getContactName() {
    return contactName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.contact_name
   *
   * @param contactName the value for tenancy.contact_name
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setContactName(String contactName) {
    this.contactName = contactName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.phone
   *
   * @return the value of tenancy.phone
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getPhone() {
    return phone;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.phone
   *
   * @param phone the value for tenancy.phone
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.description
   *
   * @return the value of tenancy.description
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public String getDescription() {
    return description;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.description
   *
   * @param description the value for tenancy.description
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.status
   *
   * @return the value of tenancy.status
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Byte getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.status
   *
   * @param status the value for tenancy.status
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setStatus(Byte status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.create_date
   *
   * @return the value of tenancy.create_date
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Date getCreateDate() {
    return createDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.create_date
   *
   * @param createDate the value for tenancy.create_date
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tenancy.last_update
   *
   * @return the value of tenancy.last_update
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Date getLastUpdate() {
    return lastUpdate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tenancy.last_update
   *
   * @param lastUpdate the value for tenancy.last_update
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public void setLastUpdate(Date lastUpdate) {
    this.lastUpdate = lastUpdate;
  }
}
