package com.dianrong.common.uniauth.server.data.entity;

public class UserTagKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_tag.tag_id
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Integer tagId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_tag.user_id
   *
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  private Long userId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_tag.tag_id
   *
   * @return the value of user_tag.tag_id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Integer getTagId() {
    return tagId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_tag.tag_id
   *
   * @param tagId the value for user_tag.tag_id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public UserTagKey setTagId(Integer tagId) {
    this.tagId = tagId;
    return this;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_tag.user_id
   *
   * @return the value of user_tag.user_id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public Long getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_tag.user_id
   *
   * @param userId the value for user_tag.user_id
   * @mbggenerated Tue Sep 27 11:53:21 CST 2016
   */
  public UserTagKey setUserId(Long userId) {
    this.userId = userId;
    return this;
  }
}
