package com.dianrong.common.uniauth.server.data.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserWorkRelationshipExample extends PageParam {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public UserWorkRelationshipExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNull() {
      addCriterion("user_id is null");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNotNull() {
      addCriterion("user_id is not null");
      return (Criteria) this;
    }

    public Criteria andUserIdEqualTo(Long value) {
      addCriterion("user_id =", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotEqualTo(Long value) {
      addCriterion("user_id <>", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThan(Long value) {
      addCriterion("user_id >", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
      addCriterion("user_id >=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThan(Long value) {
      addCriterion("user_id <", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThanOrEqualTo(Long value) {
      addCriterion("user_id <=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdIn(List<Long> values) {
      addCriterion("user_id in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotIn(List<Long> values) {
      addCriterion("user_id not in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdBetween(Long value1, Long value2) {
      addCriterion("user_id between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotBetween(Long value1, Long value2) {
      addCriterion("user_id not between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andManagerIdIsNull() {
      addCriterion("manager_id is null");
      return (Criteria) this;
    }

    public Criteria andManagerIdIsNotNull() {
      addCriterion("manager_id is not null");
      return (Criteria) this;
    }

    public Criteria andManagerIdEqualTo(Long value) {
      addCriterion("manager_id =", value, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdNotEqualTo(Long value) {
      addCriterion("manager_id <>", value, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdGreaterThan(Long value) {
      addCriterion("manager_id >", value, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdGreaterThanOrEqualTo(Long value) {
      addCriterion("manager_id >=", value, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdLessThan(Long value) {
      addCriterion("manager_id <", value, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdLessThanOrEqualTo(Long value) {
      addCriterion("manager_id <=", value, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdIn(List<Long> values) {
      addCriterion("manager_id in", values, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdNotIn(List<Long> values) {
      addCriterion("manager_id not in", values, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdBetween(Long value1, Long value2) {
      addCriterion("manager_id between", value1, value2, "managerId");
      return (Criteria) this;
    }

    public Criteria andManagerIdNotBetween(Long value1, Long value2) {
      addCriterion("manager_id not between", value1, value2, "managerId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdIsNull() {
      addCriterion("supervisor_id is null");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdIsNotNull() {
      addCriterion("supervisor_id is not null");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdEqualTo(Long value) {
      addCriterion("supervisor_id =", value, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdNotEqualTo(Long value) {
      addCriterion("supervisor_id <>", value, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdGreaterThan(Long value) {
      addCriterion("supervisor_id >", value, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdGreaterThanOrEqualTo(Long value) {
      addCriterion("supervisor_id >=", value, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdLessThan(Long value) {
      addCriterion("supervisor_id <", value, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdLessThanOrEqualTo(Long value) {
      addCriterion("supervisor_id <=", value, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdIn(List<Long> values) {
      addCriterion("supervisor_id in", values, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdNotIn(List<Long> values) {
      addCriterion("supervisor_id not in", values, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdBetween(Long value1, Long value2) {
      addCriterion("supervisor_id between", value1, value2, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andSupervisorIdNotBetween(Long value1, Long value2) {
      addCriterion("supervisor_id not between", value1, value2, "supervisorId");
      return (Criteria) this;
    }

    public Criteria andTypeIsNull() {
      addCriterion("type is null");
      return (Criteria) this;
    }

    public Criteria andTypeIsNotNull() {
      addCriterion("type is not null");
      return (Criteria) this;
    }

    public Criteria andTypeEqualTo(Byte value) {
      addCriterion("type =", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotEqualTo(Byte value) {
      addCriterion("type <>", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThan(Byte value) {
      addCriterion("type >", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
      addCriterion("type >=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThan(Byte value) {
      addCriterion("type <", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThanOrEqualTo(Byte value) {
      addCriterion("type <=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeIn(List<Byte> values) {
      addCriterion("type in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotIn(List<Byte> values) {
      addCriterion("type not in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeBetween(Byte value1, Byte value2) {
      addCriterion("type between", value1, value2, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotBetween(Byte value1, Byte value2) {
      addCriterion("type not between", value1, value2, "type");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateIsNull() {
      addCriterion("assignment_date is null");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateIsNotNull() {
      addCriterion("assignment_date is not null");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateEqualTo(Date value) {
      addCriterion("assignment_date =", value, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateNotEqualTo(Date value) {
      addCriterion("assignment_date <>", value, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateGreaterThan(Date value) {
      addCriterion("assignment_date >", value, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateGreaterThanOrEqualTo(Date value) {
      addCriterion("assignment_date >=", value, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateLessThan(Date value) {
      addCriterion("assignment_date <", value, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateLessThanOrEqualTo(Date value) {
      addCriterion("assignment_date <=", value, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateIn(List<Date> values) {
      addCriterion("assignment_date in", values, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateNotIn(List<Date> values) {
      addCriterion("assignment_date not in", values, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateBetween(Date value1, Date value2) {
      addCriterion("assignment_date between", value1, value2, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andAssignmentDateNotBetween(Date value1, Date value2) {
      addCriterion("assignment_date not between", value1, value2, "assignmentDate");
      return (Criteria) this;
    }

    public Criteria andHireDateIsNull() {
      addCriterion("hire_date is null");
      return (Criteria) this;
    }

    public Criteria andHireDateIsNotNull() {
      addCriterion("hire_date is not null");
      return (Criteria) this;
    }

    public Criteria andHireDateEqualTo(Date value) {
      addCriterion("hire_date =", value, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateNotEqualTo(Date value) {
      addCriterion("hire_date <>", value, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateGreaterThan(Date value) {
      addCriterion("hire_date >", value, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateGreaterThanOrEqualTo(Date value) {
      addCriterion("hire_date >=", value, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateLessThan(Date value) {
      addCriterion("hire_date <", value, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateLessThanOrEqualTo(Date value) {
      addCriterion("hire_date <=", value, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateIn(List<Date> values) {
      addCriterion("hire_date in", values, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateNotIn(List<Date> values) {
      addCriterion("hire_date not in", values, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateBetween(Date value1, Date value2) {
      addCriterion("hire_date between", value1, value2, "hireDate");
      return (Criteria) this;
    }

    public Criteria andHireDateNotBetween(Date value1, Date value2) {
      addCriterion("hire_date not between", value1, value2, "hireDate");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameIsNull() {
      addCriterion("business_unit_name is null");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameIsNotNull() {
      addCriterion("business_unit_name is not null");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameEqualTo(String value) {
      addCriterion("business_unit_name =", value, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameNotEqualTo(String value) {
      addCriterion("business_unit_name <>", value, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameGreaterThan(String value) {
      addCriterion("business_unit_name >", value, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameGreaterThanOrEqualTo(String value) {
      addCriterion("business_unit_name >=", value, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameLessThan(String value) {
      addCriterion("business_unit_name <", value, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameLessThanOrEqualTo(String value) {
      addCriterion("business_unit_name <=", value, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameLike(String value) {
      addCriterion("business_unit_name like", value, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameNotLike(String value) {
      addCriterion("business_unit_name not like", value, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameIn(List<String> values) {
      addCriterion("business_unit_name in", values, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameNotIn(List<String> values) {
      addCriterion("business_unit_name not in", values, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameBetween(String value1, String value2) {
      addCriterion("business_unit_name between", value1, value2, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andBusinessUnitNameNotBetween(String value1, String value2) {
      addCriterion("business_unit_name not between", value1, value2, "businessUnitName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameIsNull() {
      addCriterion("department_name is null");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameIsNotNull() {
      addCriterion("department_name is not null");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameEqualTo(String value) {
      addCriterion("department_name =", value, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameNotEqualTo(String value) {
      addCriterion("department_name <>", value, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameGreaterThan(String value) {
      addCriterion("department_name >", value, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameGreaterThanOrEqualTo(String value) {
      addCriterion("department_name >=", value, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameLessThan(String value) {
      addCriterion("department_name <", value, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameLessThanOrEqualTo(String value) {
      addCriterion("department_name <=", value, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameLike(String value) {
      addCriterion("department_name like", value, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameNotLike(String value) {
      addCriterion("department_name not like", value, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameIn(List<String> values) {
      addCriterion("department_name in", values, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameNotIn(List<String> values) {
      addCriterion("department_name not in", values, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameBetween(String value1, String value2) {
      addCriterion("department_name between", value1, value2, "departmentName");
      return (Criteria) this;
    }

    public Criteria andDepartmentNameNotBetween(String value1, String value2) {
      addCriterion("department_name not between", value1, value2, "departmentName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameIsNull() {
      addCriterion("legal_entity_name is null");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameIsNotNull() {
      addCriterion("legal_entity_name is not null");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameEqualTo(String value) {
      addCriterion("legal_entity_name =", value, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameNotEqualTo(String value) {
      addCriterion("legal_entity_name <>", value, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameGreaterThan(String value) {
      addCriterion("legal_entity_name >", value, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameGreaterThanOrEqualTo(String value) {
      addCriterion("legal_entity_name >=", value, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameLessThan(String value) {
      addCriterion("legal_entity_name <", value, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameLessThanOrEqualTo(String value) {
      addCriterion("legal_entity_name <=", value, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameLike(String value) {
      addCriterion("legal_entity_name like", value, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameNotLike(String value) {
      addCriterion("legal_entity_name not like", value, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameIn(List<String> values) {
      addCriterion("legal_entity_name in", values, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameNotIn(List<String> values) {
      addCriterion("legal_entity_name not in", values, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameBetween(String value1, String value2) {
      addCriterion("legal_entity_name between", value1, value2, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andLegalEntityNameNotBetween(String value1, String value2) {
      addCriterion("legal_entity_name not between", value1, value2, "legalEntityName");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneIsNull() {
      addCriterion("work_phone is null");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneIsNotNull() {
      addCriterion("work_phone is not null");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneEqualTo(String value) {
      addCriterion("work_phone =", value, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneNotEqualTo(String value) {
      addCriterion("work_phone <>", value, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneGreaterThan(String value) {
      addCriterion("work_phone >", value, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneGreaterThanOrEqualTo(String value) {
      addCriterion("work_phone >=", value, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneLessThan(String value) {
      addCriterion("work_phone <", value, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneLessThanOrEqualTo(String value) {
      addCriterion("work_phone <=", value, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneLike(String value) {
      addCriterion("work_phone like", value, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneNotLike(String value) {
      addCriterion("work_phone not like", value, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneIn(List<String> values) {
      addCriterion("work_phone in", values, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneNotIn(List<String> values) {
      addCriterion("work_phone not in", values, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneBetween(String value1, String value2) {
      addCriterion("work_phone between", value1, value2, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkPhoneNotBetween(String value1, String value2) {
      addCriterion("work_phone not between", value1, value2, "workPhone");
      return (Criteria) this;
    }

    public Criteria andWorkLocationIsNull() {
      addCriterion("work_location is null");
      return (Criteria) this;
    }

    public Criteria andWorkLocationIsNotNull() {
      addCriterion("work_location is not null");
      return (Criteria) this;
    }

    public Criteria andWorkLocationEqualTo(String value) {
      addCriterion("work_location =", value, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationNotEqualTo(String value) {
      addCriterion("work_location <>", value, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationGreaterThan(String value) {
      addCriterion("work_location >", value, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationGreaterThanOrEqualTo(String value) {
      addCriterion("work_location >=", value, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationLessThan(String value) {
      addCriterion("work_location <", value, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationLessThanOrEqualTo(String value) {
      addCriterion("work_location <=", value, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationLike(String value) {
      addCriterion("work_location like", value, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationNotLike(String value) {
      addCriterion("work_location not like", value, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationIn(List<String> values) {
      addCriterion("work_location in", values, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationNotIn(List<String> values) {
      addCriterion("work_location not in", values, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationBetween(String value1, String value2) {
      addCriterion("work_location between", value1, value2, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkLocationNotBetween(String value1, String value2) {
      addCriterion("work_location not between", value1, value2, "workLocation");
      return (Criteria) this;
    }

    public Criteria andWorkAddressIsNull() {
      addCriterion("work_address is null");
      return (Criteria) this;
    }

    public Criteria andWorkAddressIsNotNull() {
      addCriterion("work_address is not null");
      return (Criteria) this;
    }

    public Criteria andWorkAddressEqualTo(String value) {
      addCriterion("work_address =", value, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressNotEqualTo(String value) {
      addCriterion("work_address <>", value, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressGreaterThan(String value) {
      addCriterion("work_address >", value, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressGreaterThanOrEqualTo(String value) {
      addCriterion("work_address >=", value, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressLessThan(String value) {
      addCriterion("work_address <", value, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressLessThanOrEqualTo(String value) {
      addCriterion("work_address <=", value, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressLike(String value) {
      addCriterion("work_address like", value, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressNotLike(String value) {
      addCriterion("work_address not like", value, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressIn(List<String> values) {
      addCriterion("work_address in", values, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressNotIn(List<String> values) {
      addCriterion("work_address not in", values, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressBetween(String value1, String value2) {
      addCriterion("work_address between", value1, value2, "workAddress");
      return (Criteria) this;
    }

    public Criteria andWorkAddressNotBetween(String value1, String value2) {
      addCriterion("work_address not between", value1, value2, "workAddress");
      return (Criteria) this;
    }

    public Criteria andCreateDateIsNull() {
      addCriterion("create_date is null");
      return (Criteria) this;
    }

    public Criteria andCreateDateIsNotNull() {
      addCriterion("create_date is not null");
      return (Criteria) this;
    }

    public Criteria andCreateDateEqualTo(Date value) {
      addCriterion("create_date =", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateNotEqualTo(Date value) {
      addCriterion("create_date <>", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateGreaterThan(Date value) {
      addCriterion("create_date >", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
      addCriterion("create_date >=", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateLessThan(Date value) {
      addCriterion("create_date <", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateLessThanOrEqualTo(Date value) {
      addCriterion("create_date <=", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateIn(List<Date> values) {
      addCriterion("create_date in", values, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateNotIn(List<Date> values) {
      addCriterion("create_date not in", values, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateBetween(Date value1, Date value2) {
      addCriterion("create_date between", value1, value2, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateNotBetween(Date value1, Date value2) {
      addCriterion("create_date not between", value1, value2, "createDate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateIsNull() {
      addCriterion("last_update is null");
      return (Criteria) this;
    }

    public Criteria andLastUpdateIsNotNull() {
      addCriterion("last_update is not null");
      return (Criteria) this;
    }

    public Criteria andLastUpdateEqualTo(Date value) {
      addCriterion("last_update =", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateNotEqualTo(Date value) {
      addCriterion("last_update <>", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateGreaterThan(Date value) {
      addCriterion("last_update >", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateGreaterThanOrEqualTo(Date value) {
      addCriterion("last_update >=", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateLessThan(Date value) {
      addCriterion("last_update <", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateLessThanOrEqualTo(Date value) {
      addCriterion("last_update <=", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateIn(List<Date> values) {
      addCriterion("last_update in", values, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateNotIn(List<Date> values) {
      addCriterion("last_update not in", values, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateBetween(Date value1, Date value2) {
      addCriterion("last_update between", value1, value2, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateNotBetween(Date value1, Date value2) {
      addCriterion("last_update not between", value1, value2, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIsNull() {
      addCriterion("tenancy_id is null");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIsNotNull() {
      addCriterion("tenancy_id is not null");
      return (Criteria) this;
    }

    public Criteria andTenancyIdEqualTo(Long value) {
      addCriterion("tenancy_id =", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotEqualTo(Long value) {
      addCriterion("tenancy_id <>", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdGreaterThan(Long value) {
      addCriterion("tenancy_id >", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdGreaterThanOrEqualTo(Long value) {
      addCriterion("tenancy_id >=", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdLessThan(Long value) {
      addCriterion("tenancy_id <", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdLessThanOrEqualTo(Long value) {
      addCriterion("tenancy_id <=", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIn(List<Long> values) {
      addCriterion("tenancy_id in", values, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotIn(List<Long> values) {
      addCriterion("tenancy_id not in", values, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdBetween(Long value1, Long value2) {
      addCriterion("tenancy_id between", value1, value2, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotBetween(Long value1, Long value2) {
      addCriterion("tenancy_id not between", value1, value2, "tenancyId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated do_not_delete_during_merge Thu Jun 01 18:13:03 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * user_work_relationship
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}
