package com.dianrong.common.uniauth.server.data.entity;

public class UserExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extend.id
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extend.code
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_extend.description
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extend.id
     *
     * @return the value of user_extend.id
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extend.id
     *
     * @param id the value for user_extend.id
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extend.code
     *
     * @return the value of user_extend.code
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extend.code
     *
     * @param code the value for user_extend.code
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_extend.description
     *
     * @return the value of user_extend.description
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_extend.description
     *
     * @param description the value for user_extend.description
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}