package com.dianrong.common.uniauth.server.data.entity;

public class UserGrp extends UserGrpKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_grp.type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  private Byte type;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_grp.type
   *
   * @return the value of user_grp.type
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  public Byte getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_grp.type
   *
   * @param type the value for user_grp.type
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  public void setType(Byte type) {
    this.type = type;
  }
}
