package com.dianrong.common.uniauth.server.data.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserDetailExample extends PageParam {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public UserDetailExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    protected void addCriterionForJdbcDate(String condition, Date value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value.getTime()), property);
    }

    protected void addCriterionForJdbcDate(String condition, List<Date> values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
      Iterator<Date> iter = values.iterator();
      while (iter.hasNext()) {
        dateList.add(new java.sql.Date(iter.next().getTime()));
      }
      addCriterion(condition, dateList, property);
    }

    protected void addCriterionForJdbcDate(String condition, Date value1, Date value2,
        String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value1.getTime()),
          new java.sql.Date(value2.getTime()), property);
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNull() {
      addCriterion("user_id is null");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNotNull() {
      addCriterion("user_id is not null");
      return (Criteria) this;
    }

    public Criteria andUserIdEqualTo(Long value) {
      addCriterion("user_id =", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotEqualTo(Long value) {
      addCriterion("user_id <>", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThan(Long value) {
      addCriterion("user_id >", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
      addCriterion("user_id >=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThan(Long value) {
      addCriterion("user_id <", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThanOrEqualTo(Long value) {
      addCriterion("user_id <=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdIn(List<Long> values) {
      addCriterion("user_id in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotIn(List<Long> values) {
      addCriterion("user_id not in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdBetween(Long value1, Long value2) {
      addCriterion("user_id between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotBetween(Long value1, Long value2) {
      addCriterion("user_id not between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andFirstNameIsNull() {
      addCriterion("first_name is null");
      return (Criteria) this;
    }

    public Criteria andFirstNameIsNotNull() {
      addCriterion("first_name is not null");
      return (Criteria) this;
    }

    public Criteria andFirstNameEqualTo(String value) {
      addCriterion("first_name =", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameNotEqualTo(String value) {
      addCriterion("first_name <>", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameGreaterThan(String value) {
      addCriterion("first_name >", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
      addCriterion("first_name >=", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameLessThan(String value) {
      addCriterion("first_name <", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameLessThanOrEqualTo(String value) {
      addCriterion("first_name <=", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameLike(String value) {
      addCriterion("first_name like", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameNotLike(String value) {
      addCriterion("first_name not like", value, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameIn(List<String> values) {
      addCriterion("first_name in", values, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameNotIn(List<String> values) {
      addCriterion("first_name not in", values, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameBetween(String value1, String value2) {
      addCriterion("first_name between", value1, value2, "firstName");
      return (Criteria) this;
    }

    public Criteria andFirstNameNotBetween(String value1, String value2) {
      addCriterion("first_name not between", value1, value2, "firstName");
      return (Criteria) this;
    }

    public Criteria andLastNameIsNull() {
      addCriterion("last_name is null");
      return (Criteria) this;
    }

    public Criteria andLastNameIsNotNull() {
      addCriterion("last_name is not null");
      return (Criteria) this;
    }

    public Criteria andLastNameEqualTo(String value) {
      addCriterion("last_name =", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameNotEqualTo(String value) {
      addCriterion("last_name <>", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameGreaterThan(String value) {
      addCriterion("last_name >", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameGreaterThanOrEqualTo(String value) {
      addCriterion("last_name >=", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameLessThan(String value) {
      addCriterion("last_name <", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameLessThanOrEqualTo(String value) {
      addCriterion("last_name <=", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameLike(String value) {
      addCriterion("last_name like", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameNotLike(String value) {
      addCriterion("last_name not like", value, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameIn(List<String> values) {
      addCriterion("last_name in", values, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameNotIn(List<String> values) {
      addCriterion("last_name not in", values, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameBetween(String value1, String value2) {
      addCriterion("last_name between", value1, value2, "lastName");
      return (Criteria) this;
    }

    public Criteria andLastNameNotBetween(String value1, String value2) {
      addCriterion("last_name not between", value1, value2, "lastName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameIsNull() {
      addCriterion("display_name is null");
      return (Criteria) this;
    }

    public Criteria andDisplayNameIsNotNull() {
      addCriterion("display_name is not null");
      return (Criteria) this;
    }

    public Criteria andDisplayNameEqualTo(String value) {
      addCriterion("display_name =", value, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameNotEqualTo(String value) {
      addCriterion("display_name <>", value, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameGreaterThan(String value) {
      addCriterion("display_name >", value, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameGreaterThanOrEqualTo(String value) {
      addCriterion("display_name >=", value, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameLessThan(String value) {
      addCriterion("display_name <", value, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameLessThanOrEqualTo(String value) {
      addCriterion("display_name <=", value, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameLike(String value) {
      addCriterion("display_name like", value, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameNotLike(String value) {
      addCriterion("display_name not like", value, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameIn(List<String> values) {
      addCriterion("display_name in", values, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameNotIn(List<String> values) {
      addCriterion("display_name not in", values, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameBetween(String value1, String value2) {
      addCriterion("display_name between", value1, value2, "displayName");
      return (Criteria) this;
    }

    public Criteria andDisplayNameNotBetween(String value1, String value2) {
      addCriterion("display_name not between", value1, value2, "displayName");
      return (Criteria) this;
    }

    public Criteria andNickNameIsNull() {
      addCriterion("nick_name is null");
      return (Criteria) this;
    }

    public Criteria andNickNameIsNotNull() {
      addCriterion("nick_name is not null");
      return (Criteria) this;
    }

    public Criteria andNickNameEqualTo(String value) {
      addCriterion("nick_name =", value, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameNotEqualTo(String value) {
      addCriterion("nick_name <>", value, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameGreaterThan(String value) {
      addCriterion("nick_name >", value, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameGreaterThanOrEqualTo(String value) {
      addCriterion("nick_name >=", value, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameLessThan(String value) {
      addCriterion("nick_name <", value, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameLessThanOrEqualTo(String value) {
      addCriterion("nick_name <=", value, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameLike(String value) {
      addCriterion("nick_name like", value, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameNotLike(String value) {
      addCriterion("nick_name not like", value, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameIn(List<String> values) {
      addCriterion("nick_name in", values, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameNotIn(List<String> values) {
      addCriterion("nick_name not in", values, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameBetween(String value1, String value2) {
      addCriterion("nick_name between", value1, value2, "nickName");
      return (Criteria) this;
    }

    public Criteria andNickNameNotBetween(String value1, String value2) {
      addCriterion("nick_name not between", value1, value2, "nickName");
      return (Criteria) this;
    }

    public Criteria andIdentityNoIsNull() {
      addCriterion("identity_no is null");
      return (Criteria) this;
    }

    public Criteria andIdentityNoIsNotNull() {
      addCriterion("identity_no is not null");
      return (Criteria) this;
    }

    public Criteria andIdentityNoEqualTo(String value) {
      addCriterion("identity_no =", value, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoNotEqualTo(String value) {
      addCriterion("identity_no <>", value, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoGreaterThan(String value) {
      addCriterion("identity_no >", value, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoGreaterThanOrEqualTo(String value) {
      addCriterion("identity_no >=", value, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoLessThan(String value) {
      addCriterion("identity_no <", value, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoLessThanOrEqualTo(String value) {
      addCriterion("identity_no <=", value, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoLike(String value) {
      addCriterion("identity_no like", value, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoNotLike(String value) {
      addCriterion("identity_no not like", value, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoIn(List<String> values) {
      addCriterion("identity_no in", values, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoNotIn(List<String> values) {
      addCriterion("identity_no not in", values, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoBetween(String value1, String value2) {
      addCriterion("identity_no between", value1, value2, "identityNo");
      return (Criteria) this;
    }

    public Criteria andIdentityNoNotBetween(String value1, String value2) {
      addCriterion("identity_no not between", value1, value2, "identityNo");
      return (Criteria) this;
    }

    public Criteria andMottoIsNull() {
      addCriterion("motto is null");
      return (Criteria) this;
    }

    public Criteria andMottoIsNotNull() {
      addCriterion("motto is not null");
      return (Criteria) this;
    }

    public Criteria andMottoEqualTo(String value) {
      addCriterion("motto =", value, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoNotEqualTo(String value) {
      addCriterion("motto <>", value, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoGreaterThan(String value) {
      addCriterion("motto >", value, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoGreaterThanOrEqualTo(String value) {
      addCriterion("motto >=", value, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoLessThan(String value) {
      addCriterion("motto <", value, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoLessThanOrEqualTo(String value) {
      addCriterion("motto <=", value, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoLike(String value) {
      addCriterion("motto like", value, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoNotLike(String value) {
      addCriterion("motto not like", value, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoIn(List<String> values) {
      addCriterion("motto in", values, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoNotIn(List<String> values) {
      addCriterion("motto not in", values, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoBetween(String value1, String value2) {
      addCriterion("motto between", value1, value2, "motto");
      return (Criteria) this;
    }

    public Criteria andMottoNotBetween(String value1, String value2) {
      addCriterion("motto not between", value1, value2, "motto");
      return (Criteria) this;
    }

    public Criteria andImageIsNull() {
      addCriterion("image is null");
      return (Criteria) this;
    }

    public Criteria andImageIsNotNull() {
      addCriterion("image is not null");
      return (Criteria) this;
    }

    public Criteria andImageEqualTo(String value) {
      addCriterion("image =", value, "image");
      return (Criteria) this;
    }

    public Criteria andImageNotEqualTo(String value) {
      addCriterion("image <>", value, "image");
      return (Criteria) this;
    }

    public Criteria andImageGreaterThan(String value) {
      addCriterion("image >", value, "image");
      return (Criteria) this;
    }

    public Criteria andImageGreaterThanOrEqualTo(String value) {
      addCriterion("image >=", value, "image");
      return (Criteria) this;
    }

    public Criteria andImageLessThan(String value) {
      addCriterion("image <", value, "image");
      return (Criteria) this;
    }

    public Criteria andImageLessThanOrEqualTo(String value) {
      addCriterion("image <=", value, "image");
      return (Criteria) this;
    }

    public Criteria andImageLike(String value) {
      addCriterion("image like", value, "image");
      return (Criteria) this;
    }

    public Criteria andImageNotLike(String value) {
      addCriterion("image not like", value, "image");
      return (Criteria) this;
    }

    public Criteria andImageIn(List<String> values) {
      addCriterion("image in", values, "image");
      return (Criteria) this;
    }

    public Criteria andImageNotIn(List<String> values) {
      addCriterion("image not in", values, "image");
      return (Criteria) this;
    }

    public Criteria andImageBetween(String value1, String value2) {
      addCriterion("image between", value1, value2, "image");
      return (Criteria) this;
    }

    public Criteria andImageNotBetween(String value1, String value2) {
      addCriterion("image not between", value1, value2, "image");
      return (Criteria) this;
    }

    public Criteria andSsnIsNull() {
      addCriterion("ssn is null");
      return (Criteria) this;
    }

    public Criteria andSsnIsNotNull() {
      addCriterion("ssn is not null");
      return (Criteria) this;
    }

    public Criteria andSsnEqualTo(String value) {
      addCriterion("ssn =", value, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnNotEqualTo(String value) {
      addCriterion("ssn <>", value, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnGreaterThan(String value) {
      addCriterion("ssn >", value, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnGreaterThanOrEqualTo(String value) {
      addCriterion("ssn >=", value, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnLessThan(String value) {
      addCriterion("ssn <", value, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnLessThanOrEqualTo(String value) {
      addCriterion("ssn <=", value, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnLike(String value) {
      addCriterion("ssn like", value, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnNotLike(String value) {
      addCriterion("ssn not like", value, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnIn(List<String> values) {
      addCriterion("ssn in", values, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnNotIn(List<String> values) {
      addCriterion("ssn not in", values, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnBetween(String value1, String value2) {
      addCriterion("ssn between", value1, value2, "ssn");
      return (Criteria) this;
    }

    public Criteria andSsnNotBetween(String value1, String value2) {
      addCriterion("ssn not between", value1, value2, "ssn");
      return (Criteria) this;
    }

    public Criteria andWeiboIsNull() {
      addCriterion("weibo is null");
      return (Criteria) this;
    }

    public Criteria andWeiboIsNotNull() {
      addCriterion("weibo is not null");
      return (Criteria) this;
    }

    public Criteria andWeiboEqualTo(String value) {
      addCriterion("weibo =", value, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboNotEqualTo(String value) {
      addCriterion("weibo <>", value, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboGreaterThan(String value) {
      addCriterion("weibo >", value, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboGreaterThanOrEqualTo(String value) {
      addCriterion("weibo >=", value, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboLessThan(String value) {
      addCriterion("weibo <", value, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboLessThanOrEqualTo(String value) {
      addCriterion("weibo <=", value, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboLike(String value) {
      addCriterion("weibo like", value, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboNotLike(String value) {
      addCriterion("weibo not like", value, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboIn(List<String> values) {
      addCriterion("weibo in", values, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboNotIn(List<String> values) {
      addCriterion("weibo not in", values, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboBetween(String value1, String value2) {
      addCriterion("weibo between", value1, value2, "weibo");
      return (Criteria) this;
    }

    public Criteria andWeiboNotBetween(String value1, String value2) {
      addCriterion("weibo not between", value1, value2, "weibo");
      return (Criteria) this;
    }

    public Criteria andWechatNoIsNull() {
      addCriterion("wechat_no is null");
      return (Criteria) this;
    }

    public Criteria andWechatNoIsNotNull() {
      addCriterion("wechat_no is not null");
      return (Criteria) this;
    }

    public Criteria andWechatNoEqualTo(String value) {
      addCriterion("wechat_no =", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoNotEqualTo(String value) {
      addCriterion("wechat_no <>", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoGreaterThan(String value) {
      addCriterion("wechat_no >", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoGreaterThanOrEqualTo(String value) {
      addCriterion("wechat_no >=", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoLessThan(String value) {
      addCriterion("wechat_no <", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoLessThanOrEqualTo(String value) {
      addCriterion("wechat_no <=", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoLike(String value) {
      addCriterion("wechat_no like", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoNotLike(String value) {
      addCriterion("wechat_no not like", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoIn(List<String> values) {
      addCriterion("wechat_no in", values, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoNotIn(List<String> values) {
      addCriterion("wechat_no not in", values, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoBetween(String value1, String value2) {
      addCriterion("wechat_no between", value1, value2, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoNotBetween(String value1, String value2) {
      addCriterion("wechat_no not between", value1, value2, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andAddressIsNull() {
      addCriterion("address is null");
      return (Criteria) this;
    }

    public Criteria andAddressIsNotNull() {
      addCriterion("address is not null");
      return (Criteria) this;
    }

    public Criteria andAddressEqualTo(String value) {
      addCriterion("address =", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotEqualTo(String value) {
      addCriterion("address <>", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressGreaterThan(String value) {
      addCriterion("address >", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressGreaterThanOrEqualTo(String value) {
      addCriterion("address >=", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLessThan(String value) {
      addCriterion("address <", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLessThanOrEqualTo(String value) {
      addCriterion("address <=", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLike(String value) {
      addCriterion("address like", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotLike(String value) {
      addCriterion("address not like", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressIn(List<String> values) {
      addCriterion("address in", values, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotIn(List<String> values) {
      addCriterion("address not in", values, "address");
      return (Criteria) this;
    }

    public Criteria andAddressBetween(String value1, String value2) {
      addCriterion("address between", value1, value2, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotBetween(String value1, String value2) {
      addCriterion("address not between", value1, value2, "address");
      return (Criteria) this;
    }

    public Criteria andBirthdayIsNull() {
      addCriterion("birthday is null");
      return (Criteria) this;
    }

    public Criteria andBirthdayIsNotNull() {
      addCriterion("birthday is not null");
      return (Criteria) this;
    }

    public Criteria andBirthdayEqualTo(Date value) {
      addCriterionForJdbcDate("birthday =", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayNotEqualTo(Date value) {
      addCriterionForJdbcDate("birthday <>", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayGreaterThan(Date value) {
      addCriterionForJdbcDate("birthday >", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
      addCriterionForJdbcDate("birthday >=", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayLessThan(Date value) {
      addCriterionForJdbcDate("birthday <", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayLessThanOrEqualTo(Date value) {
      addCriterionForJdbcDate("birthday <=", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayIn(List<Date> values) {
      addCriterionForJdbcDate("birthday in", values, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayNotIn(List<Date> values) {
      addCriterionForJdbcDate("birthday not in", values, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayBetween(Date value1, Date value2) {
      addCriterionForJdbcDate("birthday between", value1, value2, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayNotBetween(Date value1, Date value2) {
      addCriterionForJdbcDate("birthday not between", value1, value2, "birthday");
      return (Criteria) this;
    }

    public Criteria andGenderIsNull() {
      addCriterion("gender is null");
      return (Criteria) this;
    }

    public Criteria andGenderIsNotNull() {
      addCriterion("gender is not null");
      return (Criteria) this;
    }

    public Criteria andGenderEqualTo(String value) {
      addCriterion("gender =", value, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderNotEqualTo(String value) {
      addCriterion("gender <>", value, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderGreaterThan(String value) {
      addCriterion("gender >", value, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderGreaterThanOrEqualTo(String value) {
      addCriterion("gender >=", value, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderLessThan(String value) {
      addCriterion("gender <", value, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderLessThanOrEqualTo(String value) {
      addCriterion("gender <=", value, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderLike(String value) {
      addCriterion("gender like", value, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderNotLike(String value) {
      addCriterion("gender not like", value, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderIn(List<String> values) {
      addCriterion("gender in", values, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderNotIn(List<String> values) {
      addCriterion("gender not in", values, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderBetween(String value1, String value2) {
      addCriterion("gender between", value1, value2, "gender");
      return (Criteria) this;
    }

    public Criteria andGenderNotBetween(String value1, String value2) {
      addCriterion("gender not between", value1, value2, "gender");
      return (Criteria) this;
    }

    public Criteria andPositionIsNull() {
      addCriterion("position is null");
      return (Criteria) this;
    }

    public Criteria andPositionIsNotNull() {
      addCriterion("position is not null");
      return (Criteria) this;
    }

    public Criteria andPositionEqualTo(String value) {
      addCriterion("position =", value, "position");
      return (Criteria) this;
    }

    public Criteria andPositionNotEqualTo(String value) {
      addCriterion("position <>", value, "position");
      return (Criteria) this;
    }

    public Criteria andPositionGreaterThan(String value) {
      addCriterion("position >", value, "position");
      return (Criteria) this;
    }

    public Criteria andPositionGreaterThanOrEqualTo(String value) {
      addCriterion("position >=", value, "position");
      return (Criteria) this;
    }

    public Criteria andPositionLessThan(String value) {
      addCriterion("position <", value, "position");
      return (Criteria) this;
    }

    public Criteria andPositionLessThanOrEqualTo(String value) {
      addCriterion("position <=", value, "position");
      return (Criteria) this;
    }

    public Criteria andPositionLike(String value) {
      addCriterion("position like", value, "position");
      return (Criteria) this;
    }

    public Criteria andPositionNotLike(String value) {
      addCriterion("position not like", value, "position");
      return (Criteria) this;
    }

    public Criteria andPositionIn(List<String> values) {
      addCriterion("position in", values, "position");
      return (Criteria) this;
    }

    public Criteria andPositionNotIn(List<String> values) {
      addCriterion("position not in", values, "position");
      return (Criteria) this;
    }

    public Criteria andPositionBetween(String value1, String value2) {
      addCriterion("position between", value1, value2, "position");
      return (Criteria) this;
    }

    public Criteria andPositionNotBetween(String value1, String value2) {
      addCriterion("position not between", value1, value2, "position");
      return (Criteria) this;
    }

    public Criteria andDepartmentIsNull() {
      addCriterion("department is null");
      return (Criteria) this;
    }

    public Criteria andDepartmentIsNotNull() {
      addCriterion("department is not null");
      return (Criteria) this;
    }

    public Criteria andDepartmentEqualTo(String value) {
      addCriterion("department =", value, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentNotEqualTo(String value) {
      addCriterion("department <>", value, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentGreaterThan(String value) {
      addCriterion("department >", value, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
      addCriterion("department >=", value, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentLessThan(String value) {
      addCriterion("department <", value, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentLessThanOrEqualTo(String value) {
      addCriterion("department <=", value, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentLike(String value) {
      addCriterion("department like", value, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentNotLike(String value) {
      addCriterion("department not like", value, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentIn(List<String> values) {
      addCriterion("department in", values, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentNotIn(List<String> values) {
      addCriterion("department not in", values, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentBetween(String value1, String value2) {
      addCriterion("department between", value1, value2, "department");
      return (Criteria) this;
    }

    public Criteria andDepartmentNotBetween(String value1, String value2) {
      addCriterion("department not between", value1, value2, "department");
      return (Criteria) this;
    }

    public Criteria andTitleIsNull() {
      addCriterion("title is null");
      return (Criteria) this;
    }

    public Criteria andTitleIsNotNull() {
      addCriterion("title is not null");
      return (Criteria) this;
    }

    public Criteria andTitleEqualTo(String value) {
      addCriterion("title =", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotEqualTo(String value) {
      addCriterion("title <>", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleGreaterThan(String value) {
      addCriterion("title >", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleGreaterThanOrEqualTo(String value) {
      addCriterion("title >=", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLessThan(String value) {
      addCriterion("title <", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLessThanOrEqualTo(String value) {
      addCriterion("title <=", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLike(String value) {
      addCriterion("title like", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotLike(String value) {
      addCriterion("title not like", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleIn(List<String> values) {
      addCriterion("title in", values, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotIn(List<String> values) {
      addCriterion("title not in", values, "title");
      return (Criteria) this;
    }

    public Criteria andTitleBetween(String value1, String value2) {
      addCriterion("title between", value1, value2, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotBetween(String value1, String value2) {
      addCriterion("title not between", value1, value2, "title");
      return (Criteria) this;
    }

    public Criteria andAidIsNull() {
      addCriterion("aid is null");
      return (Criteria) this;
    }

    public Criteria andAidIsNotNull() {
      addCriterion("aid is not null");
      return (Criteria) this;
    }

    public Criteria andAidEqualTo(Long value) {
      addCriterion("aid =", value, "aid");
      return (Criteria) this;
    }

    public Criteria andAidNotEqualTo(Long value) {
      addCriterion("aid <>", value, "aid");
      return (Criteria) this;
    }

    public Criteria andAidGreaterThan(Long value) {
      addCriterion("aid >", value, "aid");
      return (Criteria) this;
    }

    public Criteria andAidGreaterThanOrEqualTo(Long value) {
      addCriterion("aid >=", value, "aid");
      return (Criteria) this;
    }

    public Criteria andAidLessThan(Long value) {
      addCriterion("aid <", value, "aid");
      return (Criteria) this;
    }

    public Criteria andAidLessThanOrEqualTo(Long value) {
      addCriterion("aid <=", value, "aid");
      return (Criteria) this;
    }

    public Criteria andAidIn(List<Long> values) {
      addCriterion("aid in", values, "aid");
      return (Criteria) this;
    }

    public Criteria andAidNotIn(List<Long> values) {
      addCriterion("aid not in", values, "aid");
      return (Criteria) this;
    }

    public Criteria andAidBetween(Long value1, Long value2) {
      addCriterion("aid between", value1, value2, "aid");
      return (Criteria) this;
    }

    public Criteria andAidNotBetween(Long value1, Long value2) {
      addCriterion("aid not between", value1, value2, "aid");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateIsNull() {
      addCriterion("last_position_modify_date is null");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateIsNotNull() {
      addCriterion("last_position_modify_date is not null");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateEqualTo(Date value) {
      addCriterion("last_position_modify_date =", value, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateNotEqualTo(Date value) {
      addCriterion("last_position_modify_date <>", value, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateGreaterThan(Date value) {
      addCriterion("last_position_modify_date >", value, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateGreaterThanOrEqualTo(Date value) {
      addCriterion("last_position_modify_date >=", value, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateLessThan(Date value) {
      addCriterion("last_position_modify_date <", value, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateLessThanOrEqualTo(Date value) {
      addCriterion("last_position_modify_date <=", value, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateIn(List<Date> values) {
      addCriterion("last_position_modify_date in", values, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateNotIn(List<Date> values) {
      addCriterion("last_position_modify_date not in", values, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateBetween(Date value1, Date value2) {
      addCriterion("last_position_modify_date between", value1, value2, "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andLastPositionModifyDateNotBetween(Date value1, Date value2) {
      addCriterion("last_position_modify_date not between", value1, value2,
          "lastPositionModifyDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateIsNull() {
      addCriterion("entry_date is null");
      return (Criteria) this;
    }

    public Criteria andEntryDateIsNotNull() {
      addCriterion("entry_date is not null");
      return (Criteria) this;
    }

    public Criteria andEntryDateEqualTo(Date value) {
      addCriterion("entry_date =", value, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateNotEqualTo(Date value) {
      addCriterion("entry_date <>", value, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateGreaterThan(Date value) {
      addCriterion("entry_date >", value, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateGreaterThanOrEqualTo(Date value) {
      addCriterion("entry_date >=", value, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateLessThan(Date value) {
      addCriterion("entry_date <", value, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateLessThanOrEqualTo(Date value) {
      addCriterion("entry_date <=", value, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateIn(List<Date> values) {
      addCriterion("entry_date in", values, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateNotIn(List<Date> values) {
      addCriterion("entry_date not in", values, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateBetween(Date value1, Date value2) {
      addCriterion("entry_date between", value1, value2, "entryDate");
      return (Criteria) this;
    }

    public Criteria andEntryDateNotBetween(Date value1, Date value2) {
      addCriterion("entry_date not between", value1, value2, "entryDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateIsNull() {
      addCriterion("leave_date is null");
      return (Criteria) this;
    }

    public Criteria andLeaveDateIsNotNull() {
      addCriterion("leave_date is not null");
      return (Criteria) this;
    }

    public Criteria andLeaveDateEqualTo(Date value) {
      addCriterion("leave_date =", value, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateNotEqualTo(Date value) {
      addCriterion("leave_date <>", value, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateGreaterThan(Date value) {
      addCriterion("leave_date >", value, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateGreaterThanOrEqualTo(Date value) {
      addCriterion("leave_date >=", value, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateLessThan(Date value) {
      addCriterion("leave_date <", value, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateLessThanOrEqualTo(Date value) {
      addCriterion("leave_date <=", value, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateIn(List<Date> values) {
      addCriterion("leave_date in", values, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateNotIn(List<Date> values) {
      addCriterion("leave_date not in", values, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateBetween(Date value1, Date value2) {
      addCriterion("leave_date between", value1, value2, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andLeaveDateNotBetween(Date value1, Date value2) {
      addCriterion("leave_date not between", value1, value2, "leaveDate");
      return (Criteria) this;
    }

    public Criteria andRemarkIsNull() {
      addCriterion("remark is null");
      return (Criteria) this;
    }

    public Criteria andRemarkIsNotNull() {
      addCriterion("remark is not null");
      return (Criteria) this;
    }

    public Criteria andRemarkEqualTo(String value) {
      addCriterion("remark =", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkNotEqualTo(String value) {
      addCriterion("remark <>", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkGreaterThan(String value) {
      addCriterion("remark >", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkGreaterThanOrEqualTo(String value) {
      addCriterion("remark >=", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkLessThan(String value) {
      addCriterion("remark <", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkLessThanOrEqualTo(String value) {
      addCriterion("remark <=", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkLike(String value) {
      addCriterion("remark like", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkNotLike(String value) {
      addCriterion("remark not like", value, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkIn(List<String> values) {
      addCriterion("remark in", values, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkNotIn(List<String> values) {
      addCriterion("remark not in", values, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkBetween(String value1, String value2) {
      addCriterion("remark between", value1, value2, "remark");
      return (Criteria) this;
    }

    public Criteria andRemarkNotBetween(String value1, String value2) {
      addCriterion("remark not between", value1, value2, "remark");
      return (Criteria) this;
    }

    public Criteria andCreateDateIsNull() {
      addCriterion("create_date is null");
      return (Criteria) this;
    }

    public Criteria andCreateDateIsNotNull() {
      addCriterion("create_date is not null");
      return (Criteria) this;
    }

    public Criteria andCreateDateEqualTo(Date value) {
      addCriterion("create_date =", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateNotEqualTo(Date value) {
      addCriterion("create_date <>", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateGreaterThan(Date value) {
      addCriterion("create_date >", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
      addCriterion("create_date >=", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateLessThan(Date value) {
      addCriterion("create_date <", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateLessThanOrEqualTo(Date value) {
      addCriterion("create_date <=", value, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateIn(List<Date> values) {
      addCriterion("create_date in", values, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateNotIn(List<Date> values) {
      addCriterion("create_date not in", values, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateBetween(Date value1, Date value2) {
      addCriterion("create_date between", value1, value2, "createDate");
      return (Criteria) this;
    }

    public Criteria andCreateDateNotBetween(Date value1, Date value2) {
      addCriterion("create_date not between", value1, value2, "createDate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateIsNull() {
      addCriterion("last_update is null");
      return (Criteria) this;
    }

    public Criteria andLastUpdateIsNotNull() {
      addCriterion("last_update is not null");
      return (Criteria) this;
    }

    public Criteria andLastUpdateEqualTo(Date value) {
      addCriterion("last_update =", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateNotEqualTo(Date value) {
      addCriterion("last_update <>", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateGreaterThan(Date value) {
      addCriterion("last_update >", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateGreaterThanOrEqualTo(Date value) {
      addCriterion("last_update >=", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateLessThan(Date value) {
      addCriterion("last_update <", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateLessThanOrEqualTo(Date value) {
      addCriterion("last_update <=", value, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateIn(List<Date> values) {
      addCriterion("last_update in", values, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateNotIn(List<Date> values) {
      addCriterion("last_update not in", values, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateBetween(Date value1, Date value2) {
      addCriterion("last_update between", value1, value2, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andLastUpdateNotBetween(Date value1, Date value2) {
      addCriterion("last_update not between", value1, value2, "lastUpdate");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIsNull() {
      addCriterion("tenancy_id is null");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIsNotNull() {
      addCriterion("tenancy_id is not null");
      return (Criteria) this;
    }

    public Criteria andTenancyIdEqualTo(Long value) {
      addCriterion("tenancy_id =", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotEqualTo(Long value) {
      addCriterion("tenancy_id <>", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdGreaterThan(Long value) {
      addCriterion("tenancy_id >", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdGreaterThanOrEqualTo(Long value) {
      addCriterion("tenancy_id >=", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdLessThan(Long value) {
      addCriterion("tenancy_id <", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdLessThanOrEqualTo(Long value) {
      addCriterion("tenancy_id <=", value, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdIn(List<Long> values) {
      addCriterion("tenancy_id in", values, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotIn(List<Long> values) {
      addCriterion("tenancy_id not in", values, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdBetween(Long value1, Long value2) {
      addCriterion("tenancy_id between", value1, value2, "tenancyId");
      return (Criteria) this;
    }

    public Criteria andTenancyIdNotBetween(Long value1, Long value2) {
      addCriterion("tenancy_id not between", value1, value2, "tenancyId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * user_detail
   *
   * @mbggenerated do_not_delete_during_merge Thu Jun 01 18:13:03 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}
