package com.dianrong.common.techops.bean;

/**
 * 定义Techops自定义权限控制的权限类型常量.
 */
public interface PermType {

  String PERM_GROUP_OWNER = "PERM_GROUP_OWNER";
  String PERM_ORGANIZATION_OWNER = "PERM_ORGANIZATION_OWNER";
  String PERM_USERID_CHECK = "PERM_USERID_CHECK";
  String PERM_ROLEID_CHECK = "PERM_ROLEID_CHECK";
  String PERM_ROLEIDS_CHECK = "PERM_ROLEIDS_CHECK";
  String PERM_PERMID_CHECK = "PERM_PERMID_CHECK";
  String PERM_PERMIDS_CHECK = "PERM_PERMIDS_CHECK";
  String PERM_TAGTYPEID_CHECK = "PERM_TAGTYPEID_CHECK";
  String PERM_TAGID_CHECK = "PERM_TAGID_CHECK";

  String PERM_SYSTEM_USER_EDIT_CHECK = "PERM_SYSTEM_USER_EDIT_CHECK";
}
