package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.AttributeExtend;
import com.dianrong.common.uniauth.server.data.entity.AttributeExtendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeExtendMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int countByExample(AttributeExtendExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int deleteByExample(AttributeExtendExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int insert(AttributeExtend record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int insertSelective(AttributeExtend record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  List<AttributeExtend> selectByExample(AttributeExtendExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  AttributeExtend selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByExampleSelective(@Param("record") AttributeExtend record,
      @Param("example") AttributeExtendExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByExample(@Param("record") AttributeExtend record,
      @Param("example") AttributeExtendExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByPrimaryKeySelective(AttributeExtend record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * attribute_extend
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByPrimaryKey(AttributeExtend record);
  
  /**
   * 根据ProfileId获取关联的扩展属性.
   */
  List<AttributeExtend> getAttributesByProfileId(Long profileId);
}
