package com.dianrong.common.uniauth.server.data.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dianrong.common.uniauth.server.data.entity.Cfg;
import com.dianrong.common.uniauth.server.data.entity.CfgExample;

public interface CfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int countByExample(CfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int deleteByExample(CfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int insert(Cfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int insertSelective(Cfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    List<Cfg> selectByExampleWithBLOBs(CfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    List<Cfg> selectByExample(CfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    Cfg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") Cfg record, @Param("example") CfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") Cfg record, @Param("example") CfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int updateByExample(@Param("record") Cfg record, @Param("example") CfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int updateByPrimaryKeySelective(Cfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Cfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg
     *
     * @mbggenerated Tue Mar 29 15:10:36 CST 2016
     */
    int updateByPrimaryKey(Cfg record);
    
    
    /**.
     * 根据cfg_key获取有效配置的数量
     * @param cfgKey cfgKey
     * @return 数量
     */
    int countCfgByCfgKeyWithStatusEffective(@Param("cfgKey")  String cfgKey);
    
    /**.
     * 根据id获取有效配置的信息
     * @param id id
     * @return 信息model
     */
    Cfg selectByIdWithStatusEffective(@Param("id") Integer id);
}