package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.GroupRoleExample;
import com.dianrong.common.uniauth.server.data.entity.GroupRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int countByExample(GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int deleteByExample(GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int deleteByPrimaryKey(GroupRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int insert(GroupRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int insertSelective(GroupRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    List<GroupRoleKey> selectByExample(GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupRoleKey record, @Param("example") GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int updateByExample(@Param("record") GroupRoleKey record, @Param("example") GroupRoleExample example);
}