package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.GroupPath;
import com.dianrong.common.uniauth.server.data.entity.GroupPathExample;
import com.dianrong.common.uniauth.server.data.entity.GroupPathKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int countByExample(GroupPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int deleteByExample(GroupPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int deleteByPrimaryKey(GroupPathKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int insert(GroupPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int insertSelective(GroupPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    List<GroupPath> selectByExample(GroupPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    GroupPath selectByPrimaryKey(GroupPathKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupPath record, @Param("example") GroupPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int updateByExample(@Param("record") GroupPath record, @Param("example") GroupPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int updateByPrimaryKeySelective(GroupPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_path
     *
     * @mbggenerated Thu Jan 14 22:14:17 CST 2016
     */
    int updateByPrimaryKey(GroupPath record);
}