package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.GrpAttributeRecords;
import com.dianrong.common.uniauth.server.data.entity.GrpAttributeRecordsExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GrpAttributeRecordsMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int countByExample(GrpAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int deleteByExample(GrpAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int insert(GrpAttributeRecords record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int insertSelective(GrpAttributeRecords record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  List<GrpAttributeRecords> selectByExample(GrpAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  GrpAttributeRecords selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByExampleSelective(@Param("record") GrpAttributeRecords record,
      @Param("example") GrpAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByExample(@Param("record") GrpAttributeRecords record,
      @Param("example") GrpAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByPrimaryKeySelective(GrpAttributeRecords record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByPrimaryKey(GrpAttributeRecords record);

  List<GrpAttributeRecords> queryGrpHisotryProfileVal(@Param("grpId") Integer grpId,
      @Param("optDate") Date optDate, @Param("extendIds") List<Long> extendIds);
}
