package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.GrpPath;
import com.dianrong.common.uniauth.server.data.entity.GrpPathExample;
import com.dianrong.common.uniauth.server.data.entity.GrpPathKey;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface GrpPathMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int countByExample(GrpPathExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int deleteByExample(GrpPathExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int deleteByPrimaryKey(GrpPathKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int insert(GrpPath record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int insertSelective(GrpPath record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  List<GrpPath> selectByExample(GrpPathExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  GrpPath selectByPrimaryKey(GrpPathKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByExampleSelective(@Param("record") GrpPath record,
      @Param("example") GrpPathExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByExample(@Param("record") GrpPath record, @Param("example") GrpPathExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByPrimaryKeySelective(GrpPath record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_path
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByPrimaryKey(GrpPath record);

  int insertNewNode(GrpPath record);

  int moveTreeStepOne(Integer ancestor);

  int moveTreeStepTwo(Map<String, Object> paramMap);
}
