package com.dianrong.common.uniauth.server.data.mapper;

import com.codahale.metrics.annotation.Timed;
import com.dianrong.common.uniauth.server.data.entity.GrpRoleExample;
import com.dianrong.common.uniauth.server.data.entity.GrpRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GrpRoleMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  @Timed
  int countByExample(GrpRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int deleteByExample(GrpRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int deleteByPrimaryKey(GrpRoleKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int insert(GrpRoleKey record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int insertSelective(GrpRoleKey record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  @Timed
  List<GrpRoleKey> selectByExample(GrpRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByExampleSelective(@Param("record") GrpRoleKey record,
      @Param("example") GrpRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * grp_role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByExample(@Param("record") GrpRoleKey record, @Param("example") GrpRoleExample example);
}
