package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.HrDept;
import com.dianrong.common.uniauth.server.data.entity.HrDeptExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HrDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int countByExample(HrDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int deleteByExample(HrDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int deleteByPrimaryKey(Long departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int insert(HrDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int insertSelective(HrDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    List<HrDept> selectByExample(HrDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    HrDept selectByPrimaryKey(Long departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") HrDept record,
        @Param("example") HrDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int updateByExample(@Param("record") HrDept record, @Param("example") HrDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int updateByPrimaryKeySelective(HrDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_dept
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int updateByPrimaryKey(HrDept record);

    /**
     * 清空数据库表所有数据.
     */
    int clearTable();

    /**
     * 批量插入数据.
     */
    int insertBatch(List<HrDept> hrDeptList);
}
