package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.HrLe;
import com.dianrong.common.uniauth.server.data.entity.HrLeExample;
import com.dianrong.common.uniauth.server.support.audit.MapperAudit;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MapperAudit
public interface HrLeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int countByExample(HrLeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int deleteByExample(HrLeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int deleteByPrimaryKey(Long leId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int insert(HrLe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int insertSelective(HrLe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    List<HrLe> selectByExample(HrLeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    HrLe selectByPrimaryKey(Long leId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") HrLe record,
        @Param("example") HrLeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int updateByExample(@Param("record") HrLe record, @Param("example") HrLeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int updateByPrimaryKeySelective(HrLe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_le
     *
     * @mbggenerated Wed Aug 30 11:30:53 CST 2017
     */
    int updateByPrimaryKey(HrLe record);

    /**
     * 清空数据库表所有数据.
     */
    int clearTable();

    /**
     * 批量插入数据.
     */
    int insertBatch(List<HrLe> hrLeList);
}
