package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.HrSynchronousLog;
import com.dianrong.common.uniauth.server.data.entity.HrSynchronousLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HrSynchronousLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int countByExample(HrSynchronousLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int deleteByExample(HrSynchronousLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int insert(HrSynchronousLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int insertSelective(HrSynchronousLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    List<HrSynchronousLog> selectByExample(HrSynchronousLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    HrSynchronousLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") HrSynchronousLog record,
        @Param("example") HrSynchronousLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int updateByExample(@Param("record") HrSynchronousLog record,
        @Param("example") HrSynchronousLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int updateByPrimaryKeySelective(HrSynchronousLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_synchronous_log
     *
     * @mbggenerated Wed Aug 30 17:11:21 CST 2017
     */
    int updateByPrimaryKey(HrSynchronousLog record);
}
