package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.PermType;
import com.dianrong.common.uniauth.server.data.entity.PermTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermTypeMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int countByExample(PermTypeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int deleteByExample(PermTypeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int insert(PermType record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int insertSelective(PermType record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  List<PermType> selectByExample(PermTypeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  PermType selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByExampleSelective(@Param("record") PermType record,
      @Param("example") PermTypeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByExample(@Param("record") PermType record, @Param("example") PermTypeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByPrimaryKeySelective(PermType record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * perm_type
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByPrimaryKey(PermType record);
}
