package com.dianrong.common.uniauth.server.data.mapper;

import com.codahale.metrics.annotation.Timed;
import com.dianrong.common.uniauth.server.data.entity.Permission;
import com.dianrong.common.uniauth.server.data.entity.PermissionExample;
import com.dianrong.common.uniauth.server.data.entity.ext.UrlRoleMappingExt;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  @Timed
  int countByExample(PermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  int deleteByExample(PermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  int insert(Permission record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  int insertSelective(Permission record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  @Timed
  List<Permission> selectByExample(PermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  @Timed
  Permission selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  int updateByExampleSelective(@Param("record") Permission record,
      @Param("example") PermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  int updateByExample(@Param("record") Permission record,
      @Param("example") PermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  int updateByPrimaryKeySelective(Permission record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * permission
   *
   * @mbggenerated Tue Apr 05 14:00:16 CST 2016
   */
  int updateByPrimaryKey(Permission record);

  List<UrlRoleMappingExt> selectUrlRoleMapping(Map<String, Object> values);
}
