package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.ProfileDefinition;
import com.dianrong.common.uniauth.server.data.entity.ProfileDefinitionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfileDefinitionMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int countByExample(ProfileDefinitionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int deleteByExample(ProfileDefinitionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int insert(ProfileDefinition record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int insertSelective(ProfileDefinition record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  List<ProfileDefinition> selectByExample(ProfileDefinitionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  ProfileDefinition selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int updateByExampleSelective(@Param("record") ProfileDefinition record,
      @Param("example") ProfileDefinitionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int updateByExample(@Param("record") ProfileDefinition record,
      @Param("example") ProfileDefinitionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int updateByPrimaryKeySelective(ProfileDefinition record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * profile_definition
   *
   * @mbggenerated Thu Jun 15 16:06:56 CST 2017
   */
  int updateByPrimaryKey(ProfileDefinition record);
}
