package com.dianrong.common.uniauth.server.data.mapper;

import com.codahale.metrics.annotation.Timed;
import com.dianrong.common.uniauth.server.data.entity.Role;
import com.dianrong.common.uniauth.server.data.entity.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  @Timed
  int countByExample(RoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int deleteByExample(RoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int insert(Role record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int insertSelective(Role record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  @Timed
  List<Role> selectByExample(RoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  @Timed
  Role selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByPrimaryKeySelective(Role record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * role
   *
   * @mbggenerated Tue Jan 26 11:13:56 CST 2016
   */
  int updateByPrimaryKey(Role record);

  List<Integer> selectRoleIdsExtendedFromGrp(@Param("id") Long id);
}
