package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.Tag;
import com.dianrong.common.uniauth.server.data.entity.TagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int countByExample(TagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int deleteByExample(TagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int insert(Tag record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int insertSelective(Tag record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  List<Tag> selectByExample(TagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  Tag selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int updateByExampleSelective(@Param("record") Tag record, @Param("example") TagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int updateByExample(@Param("record") Tag record, @Param("example") TagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int updateByPrimaryKeySelective(Tag record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int updateByPrimaryKey(Tag record);
}
