package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.UserExtend;
import com.dianrong.common.uniauth.server.data.entity.UserExtendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserExtendMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int countByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int deleteByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int insert(UserExtend record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int insertSelective(UserExtend record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    List<UserExtend> selectByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    UserExtend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserExtend record, @Param("example") UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int updateByExample(@Param("record") UserExtend record, @Param("example") UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int updateByPrimaryKeySelective(UserExtend record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_extend
     *
     * @mbggenerated Mon May 16 11:46:03 CST 2016
     */
    int updateByPrimaryKey(UserExtend record);
}
