package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.UserExtendVal;
import com.dianrong.common.uniauth.server.data.entity.UserExtendValExample;
import com.dianrong.common.uniauth.server.data.entity.ext.UserExtendValExt;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserExtendValMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int countByExample(UserExtendValExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int deleteByExample(UserExtendValExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int insert(UserExtendVal record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int insertSelective(UserExtendVal record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  List<UserExtendVal> selectByExample(UserExtendValExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  UserExtendVal selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int updateByExampleSelective(@Param("record") UserExtendVal record,
      @Param("example") UserExtendValExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int updateByExample(@Param("record") UserExtendVal record,
      @Param("example") UserExtendValExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int updateByPrimaryKeySelective(UserExtendVal record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_extend_val
   *
   * @mbggenerated Mon May 16 11:46:03 CST 2016
   */
  int updateByPrimaryKey(UserExtendVal record);

  List<UserExtendValExt> selectByUserIdAndCode(Map<String, String> params);

  int countByCode(Map<String, String> params);

  int countByUserExtend(Map<String, String> params);

  int updateValue(@Param("userId") Long userId, @Param("extendId") Long extendId,
      @Param("value") String value);
}
