package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.UserTagExample;
import com.dianrong.common.uniauth.server.data.entity.UserTagKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTagMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int countByExample(UserTagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int deleteByExample(UserTagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int deleteByPrimaryKey(UserTagKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int insert(UserTagKey record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int insertSelective(UserTagKey record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  List<UserTagKey> selectByExample(UserTagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int updateByExampleSelective(@Param("record") UserTagKey record,
      @Param("example") UserTagExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_tag
   *
   * @mbggenerated Thu Apr 07 16:46:03 CST 2016
   */
  int updateByExample(@Param("record") UserTagKey record, @Param("example") UserTagExample example);

  /**
   * . batch insert userTag
   *
   * @param infoes insert infoes
   * @return result
   */
  int bacthInsert(@Param("infoes") List<UserTagKey> infoes);
}
