package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.UserGrpExample;
import com.dianrong.common.uniauth.server.data.entity.UserGrpKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGrpMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_grp
   *
   * @mbggenerated Tue Jan 26 16:28:33 CST 2016
   */
  int countByExample(UserGrpExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_grp
   *
   * @mbggenerated Tue Jan 26 16:28:33 CST 2016
   */
  int deleteByExample(UserGrpExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_grp
   *
   * @mbggenerated Tue Jan 26 16:28:33 CST 2016
   */
  int deleteByPrimaryKey(UserGrpKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_grp
   *
   * @mbggenerated Tue Jan 26 16:28:33 CST 2016
   */
  int insert(UserGrpKey record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_grp
   *
   * @mbggenerated Tue Jan 26 16:28:33 CST 2016
   */
  int insertSelective(UserGrpKey record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_grp
   *
   * @mbggenerated Tue Jan 26 16:28:33 CST 2016
   */
  List<UserGrpKey> selectByExample(UserGrpExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_grp
   *
   * @mbggenerated Tue Jan 26 16:28:33 CST 2016
   */
  int updateByExampleSelective(@Param("record") UserGrpKey record,
      @Param("example") UserGrpExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_grp
   *
   * @mbggenerated Tue Jan 26 16:28:33 CST 2016
   */
  int updateByExample(@Param("record") UserGrpKey record, @Param("example") UserGrpExample example);
}
