package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.UserAttributeRecords;
import com.dianrong.common.uniauth.server.data.entity.UserAttributeRecordsExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserAttributeRecordsMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int countByExample(UserAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int deleteByExample(UserAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int insert(UserAttributeRecords record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int insertSelective(UserAttributeRecords record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  List<UserAttributeRecords> selectByExample(UserAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  UserAttributeRecords selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByExampleSelective(@Param("record") UserAttributeRecords record,
      @Param("example") UserAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByExample(@Param("record") UserAttributeRecords record,
      @Param("example") UserAttributeRecordsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByPrimaryKeySelective(UserAttributeRecords record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_attribute_records
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByPrimaryKey(UserAttributeRecords record);

  List<UserAttributeRecords> queryUserHisotryProfileVal(@Param("userId") Long userId,
      @Param("optDate") Date optDate, @Param("extendIds") List<Long> extendIds);
}
