package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.UserGroupExample;
import com.dianrong.common.uniauth.server.data.entity.UserGroupKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int countByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int deleteByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int deleteByPrimaryKey(UserGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int insert(UserGroupKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int insertSelective(UserGroupKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    List<UserGroupKey> selectByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserGroupKey record, @Param("example") UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbggenerated Mon Jan 18 12:08:08 CST 2016
     */
    int updateByExample(@Param("record") UserGroupKey record, @Param("example") UserGroupExample example);
}