package com.dianrong.common.uniauth.server.data.mapper;

import com.dianrong.common.uniauth.server.data.entity.UserDetail;
import com.dianrong.common.uniauth.server.data.entity.UserDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDetailMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int countByExample(UserDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int deleteByExample(UserDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int insert(UserDetail record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int insertSelective(UserDetail record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  List<UserDetail> selectByExample(UserDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  UserDetail selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByExampleSelective(@Param("record") UserDetail record,
      @Param("example") UserDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByExample(@Param("record") UserDetail record,
      @Param("example") UserDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByPrimaryKeySelective(UserDetail record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_detail
   *
   * @mbggenerated Thu Jun 01 18:13:03 CST 2017
   */
  int updateByPrimaryKey(UserDetail record);
}
